version: '3.8'
services:
  golang:
    container_name: c0mmit_golang
    build: 
      context: ./golang
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./golang:/usr/src/app
    ports:
      - "${GO_PORT}:${GO_PORT}"
    env_file:
      - .env
    tty: true
    networks:
      - commit_net

  nodejs:
    container_name: c0mmit_nodejs
    build: 
      context: ./nodejs
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    tty: true
    networks:
      - commit_net

  postgresdb:
    container_name: c0mmit_postgres
    build: 
      context: ./postgres
      dockerfile: dockerfile
    platform: ${DB_PLATFORM:-linux/amd64}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: Asia/Tokyo
    ports:
      - "${POSTGRES_PORT}:${DEFAULT_PSQL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    tty: true
    networks:
      - commit_net

networks:
  commit_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local