version: '3.8'
services:
  golang:
    container_name: c0mmit_golang
    build: 
      context: ./golang
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./golang:/usr/src/app
    ports:
      - "${GO_PORT}:${GO_PORT}"
    env_file:
      - .env
    tty: true
    networks:
      - commit_net

  nodejs:
    container_name: c0mmit_nodejs
    build: 
      context: ./nodejs
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    tty: true
    networks:
      - commit_net

  posgredb:
    container_name: c0mmit_posgre
    build: 
      context: ./posgre
      dockerfile: dockerfile
    platform: ${DB_PLATFORM:-linux/amd64}
    env_file:
      - .env
    ports:
      - "${POSGRE_PORT}:${DEFAULT_PSQL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    tty: true
    networks:
      - commit_net

networks:
  commit_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local